version: 2.1

test_py: &test_py
  docker:
    - image: circleci/python:$PY_VERSION
  steps:
    - checkout
    - restore_cache:
        key: >
          v1-dependency-cache
          -{{ checksum "requirements/base.txt" }}
          -{{ checksum "requirements/dev.txt" }}
          -{{ checksum "scripts/install_deps_circleci.sh" }}
          -{{ .Environment.PY_VERSION }}
    - run:
        name: Install dependencies
        command: |
          python -m venv venv
          . venv/bin/activate
          sh scripts/install_deps_circleci.sh
    - save_cache:
        key: >
          v1-dependency-cache
          -{{ checksum "requirements/base.txt" }}
          -{{ checksum "requirements/dev.txt" }}
          -{{ checksum "scripts/install_deps_circleci.sh" }}
          -{{ .Environment.PY_VERSION }}
        paths:
          - "venv"
    - run:
        name: Run tests
        command: |
          . venv/bin/activate
          make lint
          pytest
    - run:
        name: Report converage
        command: |
          if [ "${PY_VERSION}" == "3.6" ]; then
            . venv/bin/activate
            codecov
          fi

jobs:
  test_py36:
    environment:
      - PY_VERSION: 3.6
      - PYTORCH_WHEEL: https://download.pytorch.org/whl/cpu/torch-1.0.0-cp36-cp36m-linux_x86_64.whl
    <<: *test_py
  test_py37:
    environment:
      - PY_VERSION: 3.7
      - PYTORCH_WHEEL: https://download.pytorch.org/whl/cpu/torch-1.0.0-cp37-cp37m-linux_x86_64.whl
    <<: *test_py
  deploy:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          name: Check git tag and version are the same
          command: |
            VERSION=$(cat VERSION)
            [ "$VERSION" = "$CIRCLE_TAG" ]
      - run:
          name: Init .pypirc
          command: |
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "username = $PYPI_USERNAME" >> ~/.pypirc
            echo -e "password = $PYPI_PASSWORD" >> ~/.pypirc
      - run:
          name: Create packages
          command: make release
      - run:
          name: Upload to pypi
          command: |
            . venv/bin/activate
            twine upload dist/*

workflows:
  version: 2.1
  buildall:
    jobs:
      - test_py36
      - test_py37
  taggedbuild:
    jobs:
      - test_py36:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - test_py37:
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
      - deploy:
          requires:
            - test_py36
            - test_py37
          filters:
            tags:
              only: /[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
