name: mltome_dev

channels:
  - pytorch
  - conda-forge

dependencies:
  - python=3.6
  - numpy=1.13.*
  - pandas=0.23.*
  - pytorch=0.4.0
  - matplotlib=2.2.*
  - feather-format=0.4.*
  - pyyaml=3.12
  - pip:
    - skorch==0.2.0
    - munch==2.3.2
    - sacred==0.7.3
